version: "3"
services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/usr/app/src

  frontend:
    build: ./web-application
    ports:
      - 80:3000
    volumes:
      - ./web-application/src:/usr/app/src
    environment:
      - REACT_APP_BACKEND_BASE_PATH=http://localhost:3000
      - REACT_APP_WSS_ADDRESS=wss://1ag0nfu7b4.execute-api.us-east-1.amazonaws.com/dev
